export 'dart:async' show FutureOr, StreamSubscription;
export 'dart:convert' show json, jsonEncode, jsonDecode, base64;
export 'dart:developer' show log;
export 'dart:io' show exit, Platform;

export 'package:another_flushbar/flushbar.dart';
export 'package:awesome_dialog/awesome_dialog.dart';
export 'package:bctpay/app_routes/routes.dart';
export 'package:bctpay/bloc/bloc.dart';
export 'package:bctpay/data/data.dart';
export 'package:bctpay/data/firebase/firebase_analytics.dart';
export 'package:bctpay/data/firebase/firebase_crashlytics.dart';
export 'package:bctpay/data/firebase/firebase_messaging.dart';
export 'package:bctpay/data/firebase/firebase_option.dart';
export 'package:bctpay/data/firebase/local_notification.dart';
export 'package:bctpay/data/repository/repository.dart';
export 'package:bctpay/data/shared_preference/shared_pref.dart';
export 'package:bctpay/extensions/capitalize.dart';
export 'package:bctpay/extensions/is_image.dart';
export 'package:bctpay/extensions/mediatype_by_file_ext.dart';
export 'package:bctpay/extensions/show4_hide_all.dart';
export 'package:bctpay/globals/assets/assets.dart';
export 'package:bctpay/globals/globals.dart';
export 'package:bctpay/helper/helper.dart';
export 'package:bctpay/l10n/generated/app_localizations.dart';
export 'package:bctpay/lib.dart';
export 'package:bctpay/main.dart';
export 'package:cached_network_image/cached_network_image.dart';
export 'package:country_flags/country_flags.dart';
export 'package:country_picker/country_picker.dart';
export 'package:document_file_save_plus/document_file_save_plus.dart';
export 'package:equatable/equatable.dart';
// export 'package:flutter_contacts/flutter_contacts.dart';
// export 'package:contacts_service/contacts_service.dart';
export 'package:fast_contacts/fast_contacts.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:firebase_messaging/firebase_messaging.dart';
export 'package:flutter/material.dart';
export 'package:flutter/services.dart';
export 'package:flutter_bloc/flutter_bloc.dart';
export 'package:flutter_dotenv/flutter_dotenv.dart';
// export 'package:flutter_gen/gen_l10n/app_localizations.dart';
export 'package:flutter_native_splash/flutter_native_splash.dart';
export 'package:flutter_staggered_animations/flutter_staggered_animations.dart';
export 'package:google_fonts/google_fonts.dart';
export 'package:image_picker/image_picker.dart';
export 'package:introduction_screen/introduction_screen.dart';
export 'package:iso8601_duration/iso8601_duration.dart';
export 'package:language_code/language_code.dart';
export 'package:loading_animation_widget/loading_animation_widget.dart';
export 'package:local_auth/local_auth.dart';
export 'package:modal_progress_hud_nsn/modal_progress_hud_nsn.dart';
export 'package:path_provider/path_provider.dart';
export 'package:pdf/pdf.dart';
export 'package:permission_handler/permission_handler.dart';
// export 'package:otp_text_field/otp_text_field.dart';
// export 'package:otp_text_field/style.dart';
export 'package:pinput/pinput.dart';
export 'package:qr_code_scanner/qr_code_scanner.dart';
export 'package:qr_code_tools/qr_code_tools.dart';
export 'package:qr_flutter/qr_flutter.dart';
export 'package:screenshot/screenshot.dart';
export 'package:share_plus/share_plus.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:tutorial_coach_mark/tutorial_coach_mark.dart';
